export const GET_CONTACTS_REQUESTED = 'GET_CONTACTS_REQUESTED';
export const GET_CONTACTS_RELOADING = 'GET_CONTACTS_RELOADING';
export const GET_CONTACTS_DONE = 'GET_CONTACTS_DONE';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';

export const ADD_CONTACT_REQUESTED = 'ADD_CONTACT_REQUESTED';
export const ADD_CONTACT_DONE = 'ADD_CONTACT_DONE';
export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED';

export const SET_CURRENT_LIMIT = 'SET_CURRENT_LIMIT';
